import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anup Poudel - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>Home</main>
    </>
  );
}
